services:
  lnd-monitor:
    build: .
    container_name: lnd-monitor
    restart: unless-stopped
    environment:
      - LND_NODE_ONION_ADDRESS=${LND_NODE_ONION_ADDRESS}
      - LND_MACAROON_RO=${LND_MACAROON_RO}
      - LND_NODE_PORT=${LND_NODE_PORT:-8080}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-120}
      - TIMEOUT=${TIMEOUT:-60}
      - CONNECTION_TIMEOUT=${CONNECTION_TIMEOUT:-45}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - CIRCUIT_REFRESH_INTERVAL=${CIRCUIT_REFRESH_INTERVAL:-300}
      - LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-7}
      - LOG_MAX_SIZE_MB=${LOG_MAX_SIZE_MB:-10}
      - TOR_CHECK_URL=${TOR_CHECK_URL:-http://check.torproject.org/api/ip}
    volumes:
      - ./data:/data   